Env: "local"
Port: "808"
AppName: "api-template"
ClientConfig:
  Timeout: 15
  IdleConnTimeout: 30
  MaxIdleConsPerHost: 1
  MaxConsPerHost: 1
ServiceConfigs:
  - Name: "WeatherService"
    URL: "https://api.weather.gov/points"
    Timeout: 60
  - Name: "GridForecastService"
    URL: "https://api.weather.gov/gridpoints/ICT"
    Timeout: 60