Env: "local"
Port: "6080"
AppName: "api-template"
ClientConfig:
  Timeout: 15
  IdleConnTimeout: 30
  MaxIdleConsPerHost: 1
  MaxConsPerHost: 1
ServiceConfigs:
  - Name: "NationalWeatherService"
    URL: "https://example.net/v5"
    Timeout: 15